### PR TITLE
Update Adam's team attributes

### PR DESCRIPTION
**Pull request by IshaDakota**
#57

Made some changes... not seeing them in the app though.

### CODE REVIEW

**Comment by amitaibu** [comment]
Thanks.

>  not seeing them in the app though.

it requires running a 2nd `gulp` under the `team_app` folder

**Comment by amitaibu** [comment]
Actually, you didn't see it since Elm didn't compile. It's Type safety dude :)

team_app_ _gulp_ _gulp_term_program_apple_terminal_ _160x44

**Comment by amitaibu** [comment]
App now works. But you have been a bit stingy with the attributes ;) Early riser? Night Owl? Listening to music at work? Languages you speak... ;)

**Comment by amitaibu** [comment]
I'll merge this, Please add more attributes in a follow up

**Comment by IshaDakota** [comment]
> But you have been a bit stingy with the attributes ;) Early riser? Night Owl? Listening to music at work? Languages you speak... ;)

Maybe I'm confused - those are in the profile (you had guessed correctly on all of those in the pre filled data)

**Pull request merged**
